### ISSUE TITLE
Verify STARC

### ISSUE THREAD

**Issue by joshua-stone** [flathub/dev.storyapps.starc#22]
I believe it should be feasible to initiate the [flathub app verification process](https://flathub-docs.vercel.app/docs/for-users/verification) for STARC:

https://flathub.org/apps/manage/dev.storyapps.starc

```
Create a page at https://storyapps.dev/.well-known/org.flathub.VerifiedApps.txt containing the following token:

97739294-2072-46b9-b779-57d9be4d257d

If the page already exists, add the token to it.
```

CC: @dimkanovikov

**Comment by dimkanovikov** [comment]
FIle added

**Comment by joshua-stone** [comment]
:tada: `Your app is currently verified by your website storyapps.dev`
